# El makefile genera tres ejecutables, ej1, ej2 y ej3.

all: ej1 ej2 ej3

ej1: 1.cpp
	g++ -std=c++11 1.cpp -o ej1  

ej2: 2.cpp
	g++ -std=c++11 2.cpp -o ej2  

ej3: 3.cpp
	g++ -std=c++11 3.cpp -o ej3 

clean:
	rm -f ej1 ej2 ej3
